using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using pfe.ecom.api.Data;
using pfe.ecom.api.Models;
using pfe.ecom.api.Services;
using System.Text;

var builder = WebApplication.CreateBuilder(args);

// DB
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException("Database connection string is missing.");

var databaseProvider = builder.Configuration["DatabaseProvider"]
    ?? throw new InvalidOperationException("Database provider is missing.");

builder.Services.AddDbContext<AppDbContext>(options =>
{
  if (databaseProvider == "SqlServer")
  {
    options.UseSqlServer(connectionString);
  }
  else if (databaseProvider == "Postgres")
  {
    options.UseNpgsql(connectionString);
  }
  else
  {
    throw new InvalidOperationException("Invalid database provider. Use 'SqlServer' or 'Postgres'.");
  }
});

// Identity
builder.Services.AddIdentityCore<ApplicationUser>(options =>
{
  options.Password.RequiredLength = 8;
  options.Password.RequireDigit = false;
  options.Password.RequireUppercase = false;
  options.Password.RequireLowercase = false;
  options.Password.RequireNonAlphanumeric = false;
  options.User.RequireUniqueEmail = true;
})
.AddRoles<IdentityRole>()
.AddEntityFrameworkStores<AppDbContext>()
.AddSignInManager()
.AddDefaultTokenProviders();

// JWT
var jwtKey = builder.Configuration["Jwt:Key"]
    ?? throw new InvalidOperationException("JWT Key is missing in configuration.");

var jwtIssuer = builder.Configuration["Jwt:Issuer"]
    ?? throw new InvalidOperationException("JWT Issuer is missing in configuration.");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
      options.TokenValidationParameters = new TokenValidationParameters
      {
        ValidateIssuer = true,
        ValidIssuer = jwtIssuer,
        ValidateAudience = false,
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
        ValidateLifetime = true,
        ClockSkew = TimeSpan.Zero,
        RoleClaimType = System.Security.Claims.ClaimTypes.Role
      };
    });

builder.Services.AddAuthorization();

// CORS
builder.Services.AddCors(options =>
{
  options.AddPolicy("frontend", policy =>
  {
    policy
        .AllowAnyOrigin()
        .AllowAnyHeader()
        .AllowAnyMethod();
  });
});

// Services
builder.Services.AddSingleton<JwtTokenService>();
builder.Services.AddScoped<ProductService>();
builder.Services.AddScoped<OrderService>();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Swagger
app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();

// Allows access to uploaded files in wwwroot/uploads/...
app.UseStaticFiles();

app.UseCors("frontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
  var services = scope.ServiceProvider;
  var db = services.GetRequiredService<AppDbContext>();

  if (db.Database.IsSqlServer())
  {
    await db.Database.MigrateAsync();
  }
  else if (db.Database.IsNpgsql())
  {
    await ApplyPostgresCompatibilitySchemaAsync(db);
  }

  await DbSeeder.SeedAsync(services);
}

app.Run();

static async Task ApplyPostgresCompatibilitySchemaAsync(AppDbContext db)
{
  await db.Database.ExecuteSqlRawAsync("""
    ALTER TABLE "AspNetUsers"
    ADD COLUMN IF NOT EXISTS "SupplierCategories" text;

    CREATE TABLE IF NOT EXISTS "OrderShippingInfos" (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "OrderId" integer NOT NULL UNIQUE,
      "FullName" character varying(120),
      "Phone" character varying(40),
      "Wilaya" character varying(80),
      "Address" character varying(500),
      "Notes" character varying(500),
      "AddressChoice" character varying(30),
      "DeliveryService" character varying(80),
      "DeliveryMode" character varying(30),
      "AgencySite" character varying(120),
      "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
      CONSTRAINT "FK_OrderShippingInfos_Orders_OrderId"
        FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "SupplierOffers" (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "Name" character varying(160) NOT NULL,
      "Category" character varying(120) NOT NULL,
      "Description" character varying(800),
      "UnitPrice" numeric(18,2) NOT NULL,
      "AvailableQuantity" integer NOT NULL,
      "MinimumQuantity" integer NOT NULL,
      "DeliveryDate" timestamp with time zone NOT NULL,
      "ImageUrl" character varying(500),
      "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
      "ProviderId" text NOT NULL,
      CONSTRAINT "FK_SupplierOffers_AspNetUsers_ProviderId"
        FOREIGN KEY ("ProviderId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "SupplyRequests" (
      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "SupplierOfferId" integer NOT NULL,
      "DealerId" text NOT NULL,
      "Quantity" integer NOT NULL,
      "TotalAmount" numeric(18,2) NOT NULL,
      "Status" character varying(40) NOT NULL,
      "PaymentMethod" character varying(40) NOT NULL,
      "PaymentStatus" character varying(40) NOT NULL,
      "RequestedAt" timestamp with time zone NOT NULL DEFAULT now(),
      "PaidAt" timestamp with time zone,
      "CancelledAt" timestamp with time zone,
      CONSTRAINT "FK_SupplyRequests_AspNetUsers_DealerId"
        FOREIGN KEY ("DealerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
      CONSTRAINT "FK_SupplyRequests_SupplierOffers_SupplierOfferId"
        FOREIGN KEY ("SupplierOfferId") REFERENCES "SupplierOffers" ("Id") ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS "IX_SupplierOffers_ProviderId" ON "SupplierOffers" ("ProviderId");
    CREATE INDEX IF NOT EXISTS "IX_SupplierOffers_Category" ON "SupplierOffers" ("Category");
    CREATE INDEX IF NOT EXISTS "IX_SupplyRequests_DealerId" ON "SupplyRequests" ("DealerId");
    CREATE INDEX IF NOT EXISTS "IX_SupplyRequests_SupplierOfferId" ON "SupplyRequests" ("SupplierOfferId");
    CREATE INDEX IF NOT EXISTS "IX_Products_Category" ON "Products" ("Category");
    CREATE INDEX IF NOT EXISTS "IX_Orders_OrderDate" ON "Orders" ("OrderDate");
    CREATE INDEX IF NOT EXISTS "IX_Orders_UserId" ON "Orders" ("UserId");
  """);
}
