// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using pfe.ecom.api.Data;

#nullable disable

namespace pfe.ecom.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512201000_AddOrderShippingInfo")]
    partial class AddOrderShippingInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
